/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('@arco-design/web-vue')['Avatar']
    ABadge: typeof import('@arco-design/web-vue')['Badge']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ADoption: typeof import('@arco-design/web-vue')['Doption']
    ADropdown: typeof import('@arco-design/web-vue')['Dropdown']
    ADropdownButton: typeof import('@arco-design/web-vue')['DropdownButton']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AMenu: typeof import('@arco-design/web-vue')['Menu']
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    APopover: typeof import('@arco-design/web-vue')['Popover']
    ARadio: typeof import('@arco-design/web-vue')['Radio']
    ARadioGroup: typeof import('@arco-design/web-vue')['RadioGroup']
    ARow: typeof import('@arco-design/web-vue')['Row']
    ArticleList: typeof import('./src/components/article-list/index.vue')['default']
    AsideBar: typeof import('./src/components/aside-bar/index.vue')['default']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ATabPane: typeof import('@arco-design/web-vue')['TabPane']
    ATabs: typeof import('@arco-design/web-vue')['Tabs']
    ATextarea: typeof import('@arco-design/web-vue')['Textarea']
    AuthorInfo: typeof import('./src/components/page-list/components/author-info/index.vue')['default']
    AuthorRank: typeof import('./src/components/author-rank/index.vue')['default']
    AvatarPanel: typeof import('./src/components/avatar-panel/index.vue')['default']
    Club: typeof import('./src/components/page-list/components/club/index.vue')['default']
    HeaderBar: typeof import('./src/components/header-bar/index.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    LinkRecommend: typeof import('./src/components/link-recommend/index.vue')['default']
    Login: typeof import('./src/components/login/index.vue')['default']
    MenuBar: typeof import('./src/components/menu-bar/index.vue')['default']
    Navigate: typeof import('./src/components/navigate/index.vue')['default']
    OperationBar: typeof import('./src/components/page-list/components/operation-bar/index.vue')['default']
    PageList: typeof import('./src/components/page-list/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiderBar: typeof import('./src/components/sider-bar/index.vue')['default']
    SignIn: typeof import('./src/components/sign-in/index.vue')['default']
    TitleBar: typeof import('./src/components/title-bar/index.vue')['default']
  }
}
